version: '3'
services:

# proxy
  proxy:
    image: proxy:v1.0.0
    ports:
      - '80:80'
      - '443:443'
      - '7600:7600'
      - '8000:8000'
    volumes:
      - /home/aderks/api.maplenodes.com/uwsgiconf:/opt/uwsgi/conf
      - /home/aderks/api.maplenodes.com/nginxconfs:/etc/nginx
      - /home/aderks/api.maplenodes.com/dhparams:/etc/pki/nginx
      - /home/aderks/api.maplenodes.com/letsencrypt:/etc/letsencrypt
      - /home/aderks/api.maplenodes.com/nginxlogs:/var/log/nginx
    container_name: proxy
    restart: unless-stopped
    logging:
      options:
        max-size: "100m"

# webserver
  webserver:
    image: webserver:v1.1.5
    ports:
      - '8192:8192'
    volumes:
      - /home/aderks/api.maplenodes.com/tmp:/xr-services/tmp
    container_name: webserver
    restart: unless-stopped
    logging:
      options:
        max-size: "100m"

